---
- name: Set zsh as default shell for {{ local_user }}
  user:
    name: "{{ local_user }}"
    shell: /usr/bin/zsh

- name: Deploy .zshrc
  copy:
    src: .zshrc
    dest: "/home/{{ local_user }}/.zshrc"
    owner: "{{ local_user }}"
    mode: '0644'
