---
- name: Copy Reaper license
  copy:
    src: licenses/reaper-license.rk
    dest: "/home/{{ local_user }}/.config/REAPER/reaper-license.rk"
    decrypt: yes
    owner: "{{ local_user }}"
    mode: '0644'

- name: Download Reaper
  get_url:
    url: "{{ reaper_download_url }}"
    dest: /tmp/reaper_linux_aarch64.tar.xz
    mode: '0644'
  when: reaper_download_url is defined

- name: Extract Reaper
  unarchive:
    src: /tmp/reaper_linux_aarch64.tar.xz
    dest: /tmp/
    remote_src: true
  when: reaper_download_url is defined

- name: Install Reaper
  shell: /tmp/reaper_linux_aarch64/install-reaper.sh --install /opt/reaper --integrate-desktop
  args:
    creates: /opt/reaper/reaper
  when: reaper_download_url is defined

- name: Create Reaper desktop entry
  copy:
    dest: /usr/share/applications/reaper.desktop
    content: |
      [Desktop Entry]
      Name=REAPER
      Exec=/opt/reaper/REAPER/reaper
      Icon=/opt/reaper/REAPER/Resources/cockos-reaper-backup.png
      Type=Application
      Categories=AudioVideo;Audio;
  when: reaper_download_url is defined
