# -*- conf -*-

[main]
font=JetBrains Mono:size=15
term=xterm
dpi-aware=no

# Shades of Purple — https://github.com/ahmadawais/shades-of-purple-vscode

[colors-dark]
background=1E1E3F
foreground=FFFFFF
selection-background=4D21FC
selection-foreground=FFFFFF

regular0=000000
regular1=EC3A37
regular2=3AD900
regular3=FAD000
regular4=7857FE
regular5=FF2C70
regular6=80FCFF
regular7=FFFFFF

bright0=5C5C61
bright1=EC3A37
bright2=3AD900
bright3=FAD000
bright4=6943FF
bright5=FB94FF
bright6=80FCFF
bright7=FFFFFF
